### ISSUE TITLE
add turkish language translation version of the book

### ISSUE THREAD

**Issue by tanersekmen** [google-research/tuning_playbook#13]
Hi,
Thanks for publishing to everyone for free,
I can help you to create an English to Turkish translation. Please let me know If I can help you with this issue.

**Comment by varungodbole** [comment]
Hi everyone,

I'm really humbled by the positive reception of this playbook! Sorry for the delay in replying to this issue. I've been a bit overwhelmed with its positive reception here and on social media. I'm sitting down right now to try to respond to everyone here and on social media. Even if I don't respond, I'm going to try to read everything.

Unfortunately, we don't have the bandwidth to support translations in multiple languages at this point. But part of the reason we launched it on GitHub was to allow folks in the community (like you!) to fork the playbook. And perhaps come up with extensions that we didn't anticipate. As I understand it, the playbook's license should allow you to make unauthorized translations and extensions. In these translations or extensions, I'd personally appreciate it if you mentioned that they're not the "official" thing, and link back to the original.

I hope that more of the ML community engages in producing best practices. Please keep filing issues as you get more ideas!

I'll leave this issue open, in case it helps you find more contributors!

**Comment by tanersekmen** [comment]
First of all, thank you for your answer.

If you need a translator from English to Turkish in any subject, I'd love to help.

Have a good day.
