### ISSUE TITLE
Any plan for multi-langauge translated version?

### ISSUE THREAD

**Issue by YeonwooSung** [google-research/tuning_playbook#15]
Hello, thank you for the great work.
Just curious, do you have any plan for making some multi-language translated version of this great repo?
Thanks :)

**Comment by varungodbole** [comment]
Hi @YeonwooSung,

I'm really humbled by the positive reception of this playbook! Sorry for the delay in replying to this issue. I've been a bit overwhelmed with its positive reception here and on social media. I'm sitting down right now to try to respond to everyone here and on social media. Even if I don't respond, I'm going to try to read everything.

Unfortunately, we don't have the bandwidth to support translations in multiple languages at this point. But part of the reason we launched it on GitHub was to allow folks in the community (like you!) to fork the playbook. And perhaps come up with extensions that we didn't anticipate. As I understand it, the playbook's license should allow you to make unauthorized translations and extensions. In these translations or extensions, I'd personally appreciate it if you mentioned that they're not the "official" thing, and link back to the original.

I hope that more of the ML community engages in producing best practices. Please keep filing issues as you get more ideas!

I'm going to close this issue for now. But if you'd like to organize the community around a specific translation, feel free to start an issue. While we wouldn't be able to officially support it, I can certainly leave those issues open to help you find other collaborators.
