### ISSUE TITLE
Add Chinese version of this document

### ISSUE THREAD

**Issue by 21zhouyun** [google-research/tuning_playbook#18]
I can help with creating a Chinese translation of this document. Please let me know if I can help with this issue.

**Comment by RangeKing** [comment]
@21zhouyun https://github.com/google-research/tuning_playbook/issues/12
I've done a rough translation of the full document with google api and polish the first two sections.
Maybe we can work togather?

**Comment by RangeKing** [comment]
> Maybe I can do section 3 and 4 (Guide for starting a new project, A scientific approach to improving model performance). You can finish the rest. I think that roughly splits the workload in half.

All my works are in [this branch](https://github.com/RangeKing/tuning_playbook_zh-CN/tree/zh-CN). I've already translated some part of the section 3. Could you please start from the section 4? And then create pull request to [this branch](https://github.com/RangeKing/tuning_playbook_zh-CN/tree/zh-CN).

**Comment by 21zhouyun** [comment]
> > Maybe I can do section 3 and 4 (Guide for starting a new project, A scientific approach to improving model performance). You can finish the rest. I think that roughly splits the workload in half.
> 
> All my works are in [this branch](https://github.com/RangeKing/tuning_playbook_zh-CN/tree/zh-CN). I've already translated some part of the section 3. Could you please start from the section 4? And then create pull request to [this branch](https://github.com/RangeKing/tuning_playbook_zh-CN/tree/zh-CN).

Sounds good. I'll work on section 4.

**Comment by varungodbole** [comment]
Hi everyone,

I'm really humbled by the positive reception of this playbook! Sorry for the delay in replying to this issue. I've been a bit overwhelmed with its positive reception here and on social media. I'm sitting down right now to try to respond to everyone here and on social media. Even if I don't respond, I'm going to try to read everything.

Unfortunately, we don't have the bandwidth to support translations in multiple languages at this point. But part of the reason we launched it on GitHub was to allow folks in the community (like you!) to fork the playbook. And perhaps come up with extensions that we didn't anticipate. As I understand it, the playbook's license should allow you to make unauthorized translations and extensions. In these translations or extensions, I'd personally appreciate it if you mentioned that they're not the "official" thing, and link back to the original.

I hope that more of the ML community engages in producing best practices. Please keep filing issues as you get more ideas!

I'll leave this issue open, in case it helps you find more contributors!

**Comment by r-asou** [comment]
Hi Varun,

We have done the whole translation for this document in simplified chinese. 
You can check our [pull request](https://github.com/google-research/tuning_playbook/pull/36)

**Comment by varungodbole** [comment]
Thanks for the pointer! Unfortunately, we don't feel comfortable endorsing any of our forks in other languages on the main page, because we can't read those languages. But thank you for helping the community with your translation!
