### ISSUE TITLE
Delphi process

### ISSUE THREAD

**Issue by alexkarargyris** [google-research/tuning_playbook#20]
Great starting document. I highly recommend that a Delphi process (https://en.wikipedia.org/wiki/Delphi_method) with the larger ML community should be pursued. See example here: https://arxiv.org/pdf/2206.01653.pdf

**Comment by varungodbole** [comment]
Thanks for the pointer! We won't have the bandwidth to pursue this for the foreseeable future. But you're welcome to pursue it and create a fork of our repository as necessary!
