### ISSUE TITLE
Wrong link in url under #citing

### ISSUE THREAD

**Issue by tha00** [google-research/tuning_playbook#21]
Thanks for the nice resource!

I believe there is a typo in the [Citing section](https://github.com/google-research/tuning_playbook#citing):

Should be
`url = {http://github.com/google-research/tuning_playbook}`

instead of
`url = {http://github.com/google/tuning_playbook}`

**Comment by Michaelgathara** [comment]
Opened a PR fixing this

**Comment by JatinKumar001** [comment]
Can I do this?
