### ISSUE TITLE
Publish playbook on GitHub Pages

### ISSUE THREAD

**Issue by ajndkr** [google-research/tuning_playbook#24]
Can we publish this repository on GitHub Pages for ease of accessibility? The process to do so seems quite simple to execute and would be a great addition to this repository.

**Comment by varungodbole** [comment]
Hey @ajndkr, thanks for the suggestion! Unfortunately, I won't have the bandwidth to do that for a while. But you're welcome to fork our repository and host it yourself, and cite back the original repo.
