### ISSUE TITLE
Evidence for Norm(x + f(x)) causing issues?

### ISSUE THREAD

**Issue by hennels** [google-research/tuning_playbook#31]
In the section on **Potential fixes for common instability patterns** there is a line stating:
```
Norm(x + f(x)) known to cause issues.
```
[Text is here](https://github.com/google-research/tuning_playbook/blob/890cd5387477a5ea1b3a7a40fe4ad1d077f54151/README.md?plain=1#L1860).

Are there any experiments or papers that you could reference to support this? I just found it very surprising considering that many recent Transformer-based architectures use exactly this pattern.

**Comment by thegr8wang** [comment]
Here it may mean that no further `Norm` is required after the residual connection.

**Comment by fzyzcjy** [comment]
+1 Do you find the answer? Thanks!

**Comment by znado** [comment]
https://arxiv.org/abs/2110.04369 discusses pre vs post LN in the context of stability.

https://arxiv.org/abs/2206.00330 has another example (although I am not as familiar with the paper and cannot couch either way for their new method).
