### ISSUE TITLE
[BUG] In Choosing the goal for the next round of experiments

### ISSUE THREAD

**Issue by SwordFaith** [google-research/tuning_playbook#43]
I guess greedily maximize validation error should be minimize validation error.

Example goals include:
- Try a potential improvement to the pipeline (e.g. a new regularizer, preprocessing choice, etc.).
- Understand the impact of a particular model hyperparameter (e.g. the activation function)
- Greedily maximize validation error.

**Comment by varungodbole** [comment]
Thanks for the pointer. It looks like this has been fixed in the main branch now. Maybe another PR fixed it?

https://github.com/google-research/tuning_playbook?tab=readme-ov-file#choosing-the-goal-for-the-next-round-of-experiments

Please reopen the issue or file another one if we missed anything.
