### ISSUE TITLE
Question: Time Series Missing Data?

### ISSUE THREAD

**Issue by fdelcab** [google-research/tuning_playbook#46]
Hi everyone, 

I would like to know your opinion about seqtopoint deep learning models for forecasting and missing data.
I am dealing with a time series that has a lot of time discontinuity data, so when I resample the data, e.g. to 1 minute, I end up with a bunch of missing gaps.

1. Should I include them in the input data (e.g. for a LSTM model) so I don't loose the time continuity characteristic of my time series?
2. Will the NaN values will help in the generalization of the model, since they can be related with noisy data? 
3. How does LSTM model handles missing data (NaN values)?

Thank you for your time

**Comment by joker507** [comment]
Missing values can be completed using a variety of strategies, such as 0 fill, linear fill, fill with adjacent values, etc. There may be more advanced methods. I don't know how to evaluate performance between these methods

**Comment by varungodbole** [comment]
Hey, this is a really great question. We believe that it's a bit outside the scope of the playbook, and we don't have any specific recommendations. So we're closing this issue for now.
