### ISSUE TITLE
Why "Normalization should be the last operation before the residual" ?

### ISSUE THREAD

**Issue by Yura52** [google-research/tuning_playbook#50]
Hi! Thanks for the great repository!

I have a question about [this line](https://github.com/google-research/tuning_playbook/blob/1760458aa9cb18ff0d12e12e9acb850f047e9f6c/README.md?plain=1#L1864) which says `Normalization should be the last operation before the residual. E.g. x + Norm(f(x))`.

I am curious what is the intuition behind this advice? Or maybe there are mainstream architectures that follow this guidline or papers explaining this aspect?

**Comment by hennels** [comment]
I think this was stated to be a typo in the discussions. https://github.com/google-research/tuning_playbook/discussions/3#discussioncomment-4732988

**Comment by Yura52** [comment]
Thank you for the reply!
