### ISSUE TITLE
How to examining the training curves about a multi-task learning model?

### ISSUE THREAD

**Issue by JohnHerry** [google-research/tuning_playbook#59]
I had read the part about how to read training curves,   Is that questions still ok for a multi-task training pipeline?

**Comment by varungodbole** [comment]
Yeah our advice should still be relevant for a multi-task setting. Often in multi-task settings, you can make your life easier if you come up with a single loss that is a function of all the different tasks. And attempt to directly optimize that.

**Comment by JohnHerry** [comment]
Thanks for the help！
