### ISSUE TITLE
Typo: Missing parenthesis in nesterov momentum

### ISSUE THREAD

**Issue by dsuedholt** [google-research/tuning_playbook#7]
FAQs -> What are the update rules for all the popular optimization algorithms? -> Nesterov

A closing parenthesis is missing in the third equation. It's currently

$$\theta_{t+1} = \theta_{t} - \eta_t( \gamma v_{t+1} + \nabla \mathcal{l}(\theta_{t})$$

and should be 

$$\theta_{t+1} = \theta_{t} - \eta_t( \gamma v_{t+1} + \nabla \mathcal{l}(\theta_{t}))$$

**Comment by JatinKumar001** [comment]
Hey, can I work on this typo?

**Comment by varungodbole** [comment]
Thanks for pointing this out! Please feel free to send me a pull request.

**Comment by varungodbole** [comment]
I think @znado just merged the PR to fix this. Closing this issue for now.
